# Generated by Django 5.2.5 on 2026-10-09 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('title_bn', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('editor', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(default='Cheradip', max_length=255)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=32)),
                ('language', models.CharField(db_index=True, default='Bangla', max_length=80)),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('book_type', models.CharField(choices=[('test_paper', 'Test Paper'), ('job_solution', 'Job Solution'), ('admission_guide', 'Admission Guide'), ('academic_guide', 'Academic Guide'), ('teacher_guide', 'Teacher Guide'), ('textbook', 'Textbook'), ('grammar', 'Grammar'), ('story', 'Story / Fiction'), ('literature', 'Literature'), ('writer_book', "Writer's Book"), ('reference', 'Reference'), ('creative', 'Creative / Essay'), ('other', 'Other')], db_index=True, default='other', max_length=40)),
                ('audience', models.CharField(choices=[('student', 'Students'), ('job_seeker', 'Job Seekers'), ('teacher', 'Teachers'), ('children', 'Children'), ('general', 'General Readers')], db_index=True, default='student', max_length=30)),
                ('source_type', models.CharField(choices=[('question_sets', 'Created from question sets'), ('exam_sets', 'Created from exam sets'), ('uploaded', 'Uploaded publication'), ('manual', 'Written manually')], default='uploaded', max_length=30)),
                ('source_config', models.JSONField(blank=True, default=dict, help_text='Question/exam set IDs, curriculum filters, section order and generation options.')),
                ('cover_image', models.FileField(blank=True, upload_to='ebooks/covers/')),
                ('wide_cover_image', models.FileField(blank=True, upload_to='ebooks/covers/wide/')),
                ('cover_design', models.JSONField(blank=True, default=dict, help_text='Smart cover colours, title placement and logo settings.')),
                ('preview_text', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, max_length=1000)),
                ('digital_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hard_copy_available', models.BooleanField(db_index=True, default=False)),
                ('hard_copy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hard_copy_quantity', models.PositiveIntegerField(default=0)),
                ('weight_grams', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=1000)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_record', to='ecommerce.product')),
            ],
            options={
                'db_table': 'ecommerce_book',
                'ordering': ('-featured', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='BookAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('ebook', 'eBook'), ('sample', 'Sample'), ('video', 'Video'), ('audio', 'Audio'), ('worksheet', 'Worksheet'), ('supplement', 'Supplement')], default='ebook', max_length=20)),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('html', 'HTML'), ('epub', 'EPUB'), ('txt', 'Text'), ('mp4', 'MP4'), ('webm', 'WebM'), ('mp3', 'MP3'), ('url', 'External URL'), ('other', 'Other')], default='pdf', max_length=20)),
                ('file', models.FileField(blank=True, upload_to='ebooks/files/')),
                ('external_url', models.URLField(blank=True, max_length=1000)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ecommerce.book')),
            ],
            options={
                'db_table': 'ecommerce_book_asset',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BookBuildJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('building', 'Building'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('html', 'HTML'), ('epub', 'EPUB')], default='pdf', max_length=12)),
                ('source_config', models.JSONField(blank=True, default=dict)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_jobs', to='ecommerce.book')),
                ('result_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_results', to='ecommerce.bookasset')),
            ],
            options={
                'db_table': 'ecommerce_book_build_job',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status', 'book_type'], name='ecommerce_b_status_4b858f_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['audience', 'language'], name='ecommerce_b_audienc_e57bfb_idx'),
        ),
    ]
