# Generated by Django 5.2.5 on 2026-10-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_book_bookasset_bookbuildjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('wallet', 'Cheradip Wallet'), ('cod', 'Cash on delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank transfer'), ('card', 'Card'), ('other', 'Other')], max_length=20),
        ),
    ]
