# Generated by Django 5.2.5 on 2026-03-12 09:16

import cheradip.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'cheradip_notification',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('acctype', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('JobSeeker', 'Job Seeker')], default='Student', max_length=12)),
                ('username', models.CharField(db_index=True, max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('fullName', models.CharField(max_length=31)),
                ('group', models.CharField(blank=True, default='Science', max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Common', 'Common')], default='', max_length=10)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher_level', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher_subject_code', models.CharField(blank=True, max_length=10, null=True)),
                ('teacher_department_code', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher_department_name', models.CharField(blank=True, max_length=200, null=True)),
                ('division', models.CharField(blank=True, default='', max_length=31)),
                ('district', models.CharField(blank=True, default='', max_length=31)),
                ('thana', models.CharField(blank=True, default='', max_length=31)),
                ('union', models.CharField(blank=True, default='', max_length=31)),
                ('village', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_alternate', models.CharField(blank=True, max_length=11, null=True)),
                ('whatsapp_apikey', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='customer_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customer_set', to='auth.permission')),
            ],
            options={
                'db_table': 'cheradip_customers',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(db_index=True, max_length=2, primary_key=True, serialize=False)),
                ('country_code_alpha3', models.CharField(blank=True, max_length=3, null=True)),
                ('country_code_numeric', models.CharField(blank=True, max_length=3, null=True)),
                ('country_name', models.CharField(max_length=60)),
                ('country_name_native', models.CharField(blank=True, max_length=60, null=True)),
                ('country_name_official', models.CharField(blank=True, max_length=100, null=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('flag_url', models.URLField(blank=True, max_length=255, null=True)),
                ('phone_code', models.CharField(max_length=5)),
                ('phone_code_numeric', models.IntegerField(blank=True, null=True)),
                ('phone_format', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_length_min', models.IntegerField(default=10)),
                ('phone_length_max', models.IntegerField(default=10)),
                ('continent', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('capital', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('currency_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('language_codes', models.JSONField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('time_display', models.CharField(blank=True, max_length=20, null=True)),
                ('display_order', models.IntegerField(default=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', cheradip.models.DateTimeFieldSafeTZ(auto_now_add=True)),
                ('updated_at', cheradip.models.DateTimeFieldSafeTZ(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'cheradip_country',
                'ordering': ['display_order', 'country_name'],
                'indexes': [models.Index(fields=['country_code'], name='cheradip_co_country_3ddee6_idx'), models.Index(fields=['country_name'], name='cheradip_co_country_629d23_idx'), models.Index(fields=['phone_code'], name='cheradip_co_phone_c_281f4b_idx'), models.Index(fields=['is_featured', 'display_order'], name='cheradip_co_is_feat_93e83b_idx'), models.Index(fields=['continent'], name='cheradip_co_contine_205e8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cheradip_customer_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cheradip_customer_tokens',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_index=True, max_length=4, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=63, null=True)),
                ('bangla_name', models.CharField(blank=True, max_length=63, null=True)),
                ('size', models.CharField(blank=True, choices=[('nctb', 'NCTB'), ('book', 'Book'), ('guide', 'Guide'), ('cheradip', 'Cheradip')], max_length=14, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('love', models.BooleanField(default=False)),
                ('add_to_cart', models.BooleanField(default=False)),
                ('in_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/items/')),
                ('videos', models.URLField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=54, null=True)),
                ('types', models.CharField(choices=[('science', 'Science'), ('business', 'Business'), ('humanities', 'Humanities'), ('compulsory', 'Compulsory'), ('sac', 'SAC'), ('ac', 'AC'), ('sc', 'SC')], default='humanities', max_length=15)),
                ('product_type', models.CharField(blank=True, choices=[('package', 'Education Package'), ('book', 'Book'), ('service', 'Question-making / Service'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('reviews', models.TextField(blank=True, default='Rated By @Author', null=True)),
                ('ratings', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping', models.TextField(blank=True, default='NA', null=True)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('dbbl', 'DBBL'), ('other', 'Other')], default='bkash', max_length=28)),
                ('details', models.TextField(blank=True, default='NA', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cheradip_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='cheradip_it_code_81532a_idx'), models.Index(fields=['types'], name='cheradip_it_types_cc2590_idx'), models.Index(fields=['name'], name='cheradip_it_name_5fc92f_idx'), models.Index(fields=['product_type'], name='cheradip_it_product_762e9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('data_type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cheradip_json_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['data_type'], name='cheradip_js_data_ty_eda6ca_idx'), models.Index(fields=['created_at'], name='cheradip_js_created_7c5b22_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('thana', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('local_address', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='cheradip.country')),
            ],
            options={
                'db_table': 'cheradip_location',
                'ordering': ['country', 'division', 'district', 'thana'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SN', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=127)),
                ('Image', models.URLField(blank=True, null=True)),
                ('Weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('Price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('Quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('Discount', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('Total', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('GrandTotal', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('Paid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('Due', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('ShipingCost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_details', to='cheradip.item')),
            ],
            options={
                'db_table': 'cheradip_orderdetail',
                'ordering': ['SN'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trxid', models.CharField(db_index=True, max_length=31, unique=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('paidFrom', models.CharField(blank=True, default='', max_length=31)),
                ('Paid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('dbbl', 'DBBL'), ('rocket', 'Rocket'), ('cash', 'Cash')], default='bkash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cheradip_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trxid'], name='cheradip_tr_trxid_945175_idx'), models.Index(fields=['username'], name='cheradip_tr_usernam_e81d14_idx'), models.Index(fields=['status', 'created_at'], name='cheradip_tr_status_b514b9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['username'], name='cheradip_cu_usernam_ae7fed_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='cheradip_cu_email_feaf04_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['acctype'], name='cheradip_cu_acctype_1a9516_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['division', 'district'], name='cheradip_cu_divisio_37b78d_idx'),
        ),
        migrations.AddIndex(
            model_name='customertoken',
            index=models.Index(fields=['key'], name='cheradip_cu_key_38fa62_idx'),
        ),
        migrations.AddIndex(
            model_name='customertoken',
            index=models.Index(fields=['customer', 'created'], name='cheradip_cu_custome_7f31f0_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['division', 'district'], name='cheradip_lo_divisio_10eda3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['item'], name='cheradip_or_item_id_256299_idx'),
        ),
    ]
