# Generated by Django 5.0.6 on 2024-09-19 17:44

import cheradip.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_name', models.CharField(default='', max_length=50)),
                ('group_code', models.CharField(max_length=1, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institute_code', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('institute_name', models.CharField(blank=True, max_length=127, unique=True)),
                ('institute_type', models.CharField(blank=True, max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, null=True)),
                ('name', models.CharField(max_length=63, null=True)),
                ('bangla_name', models.CharField(max_length=63, null=True)),
                ('size', models.CharField(choices=[('nctb', 'nctb'), ('book', 'book'), ('guide', 'guide'), ('cheradip', 'cheradip')], max_length=14, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('love', models.BooleanField(default=False, null=True)),
                ('add_to_cart', models.BooleanField(default=False, null=True)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=2, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('supplier', models.CharField(max_length=54, null=True)),
                ('types', models.CharField(choices=[('science', 'science'), ('business', 'business'), ('humanities', 'hamanities'), ('compulsory', 'compulsory'), ('sac', 'sac'), ('ac', 'ac'), ('sc', 'sc')], default='humanities', max_length=15, null=True)),
                ('reviews', models.TextField(default='Rated By @Author', null=True)),
                ('ratings', models.DecimalField(decimal_places=2, default='5', max_digits=3, null=True)),
                ('shipping', models.TextField(default='NA', max_length=14, null=True)),
                ('in_stock', models.IntegerField(null=True)),
                ('payment_method', models.CharField(choices=[('Cash on Deilivery', 'cod'), ('bKash', 'bkash'), ('Nagad', 'nagad'), ('DBBL', 'dbbl'), ('Other', 'other')], default='bKash', max_length=28, null=True)),
                ('details', models.TextField(default='NA', max_length=512, null=True)),
                ('videos', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1024, null=True)),
                ('link', models.URLField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('trxid', models.CharField(default='', max_length=31, unique=True)),
                ('paidFrom', models.CharField(default='', max_length=31)),
                ('Paid', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('year_name', models.CharField(blank=True, max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('acctype', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=7)),
                ('fullName', models.CharField(max_length=31)),
                ('username', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('group', models.CharField(choices=[('Science', 'Science'), ('Business Studies', 'Business Studies'), ('Humanities', 'Humanities')], default='Science', max_length=18)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Common', 'Common')], default='Male', max_length=6)),
                ('division', models.CharField(max_length=31)),
                ('district', models.CharField(max_length=31)),
                ('thana', models.CharField(max_length=31)),
                ('union', models.CharField(blank=True, max_length=31)),
                ('village', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, related_name='customer_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customer_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cheradip.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.IntegerField()),
                ('Name', models.CharField(max_length=127)),
                ('Image', models.URLField()),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('Price', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('Quantity', models.IntegerField(null=True)),
                ('Discount', models.DecimalField(decimal_places=0, max_digits=9, null=True)),
                ('Total', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('GrandTotal', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('Paid', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('Due', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('ShipingCost', models.DecimalField(decimal_places=0, max_digits=8, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cheradip.item')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('subject_name', models.CharField(blank=True, max_length=50)),
                ('group', models.ManyToManyField(related_name='subjects', to='cheradip.group')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.CharField(blank=True, max_length=2)),
                ('chapter_name', models.CharField(blank=True, max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='cheradip.subject')),
            ],
            options={
                'unique_together': {('subject', 'chapter_no')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_no', models.CharField(blank=True, max_length=2)),
                ('topic_name', models.CharField(blank=True, max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='cheradip.chapter')),
            ],
            options={
                'unique_together': {('chapter', 'topic_no')},
            },
        ),
        migrations.CreateModel(
            name='Ordered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=31, null=True)),
                ('district', models.CharField(blank=True, max_length=31, null=True)),
                ('thana', models.CharField(blank=True, max_length=31, null=True)),
                ('paymentMethod', models.CharField(blank=True, max_length=31, null=True)),
                ('username', models.CharField(max_length=11)),
                ('fullName', models.CharField(blank=True, max_length=31, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('union', models.CharField(blank=True, max_length=31, null=True)),
                ('village', models.TextField(blank=True, max_length=255, null=True)),
                ('altMobileNo', models.CharField(blank=True, max_length=11, null=True)),
                ('shipped', models.BooleanField(default=False)),
                ('orderDetails', models.ManyToManyField(blank=True, to='cheradip.orderdetail')),
                ('transaction', models.ManyToManyField(blank=True, to='cheradip.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=31, null=True)),
                ('district', models.CharField(blank=True, max_length=31, null=True)),
                ('thana', models.CharField(blank=True, max_length=31, null=True)),
                ('paymentMethod', models.CharField(blank=True, max_length=31, null=True)),
                ('username', models.CharField(max_length=11)),
                ('fullName', models.CharField(blank=True, max_length=31, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('union', models.CharField(blank=True, max_length=31, null=True)),
                ('village', models.TextField(blank=True, max_length=255, null=True)),
                ('altMobileNo', models.CharField(blank=True, max_length=11, null=True)),
                ('shipped', models.BooleanField(default=False)),
                ('orderDetails', models.ManyToManyField(blank=True, to='cheradip.orderdetail')),
                ('transaction', models.ManyToManyField(blank=True, to='cheradip.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Canceled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=31, null=True)),
                ('district', models.CharField(blank=True, max_length=31, null=True)),
                ('thana', models.CharField(blank=True, max_length=31, null=True)),
                ('paymentMethod', models.CharField(blank=True, max_length=31, null=True)),
                ('username', models.CharField(max_length=11)),
                ('fullName', models.CharField(blank=True, max_length=31, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('union', models.CharField(blank=True, max_length=31, null=True)),
                ('village', models.TextField(blank=True, max_length=255, null=True)),
                ('altMobileNo', models.CharField(blank=True, max_length=11, null=True)),
                ('shipped', models.BooleanField(default=False)),
                ('orderDetails', models.ManyToManyField(blank=True, to='cheradip.orderdetail')),
                ('transaction', models.ManyToManyField(blank=True, to='cheradip.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Mcq_ict',
            fields=[
                ('qid', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('uddipok', models.TextField(blank=True, max_length=1000, null=True)),
                ('question', models.TextField(max_length=300)),
                ('option1', models.TextField(max_length=200)),
                ('option2', models.TextField(max_length=200)),
                ('option3', models.TextField(max_length=200)),
                ('option4', models.TextField(max_length=200)),
                ('answer', models.CharField(choices=[('1', 'ক'), ('2', 'খ'), ('3', 'গ'), ('4', 'ঘ')], max_length=1)),
                ('explanation', models.TextField(blank=True, max_length=1000, null=True)),
                ('img_uddipok', models.ImageField(blank=True, null=True, upload_to=cheradip.models.question_image_path)),
                ('img_question', models.ImageField(blank=True, null=True, upload_to=cheradip.models.question_image_path)),
                ('img_explanation', models.ImageField(blank=True, null=True, upload_to=cheradip.models.question_image_path)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cheradip.chapter')),
                ('institute', models.ManyToManyField(related_name='questions', to='cheradip.institute')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cheradip.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cheradip.topic')),
                ('years', models.ManyToManyField(related_name='questions', to='cheradip.year')),
            ],
        ),
    ]
