# Generated by Django 5.0.6 on 2024-09-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq_ict',
            old_name='institute',
            new_name='institutes',
        ),
    ]
