# Generated by Django 5.0.6 on 2024-09-02 23:02

import cheradip.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(choices=[('Science', 'Science'), ('Business Studies', 'Business Studies'), ('Humanities', 'Humanities')], default='Science', max_length=50)),
                ('group_code', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1024, null=True)),
                ('link', models.URLField(blank=True, max_length=512, null=True)),
                ('category', models.URLField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='probable_weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='variants',
        ),
        migrations.AddField(
            model_name='customer',
            name='acctype',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=7),
        ),
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.CharField(choices=[('Science', 'Science'), ('Business Studies', 'Business Studies'), ('Humanities', 'Humanities')], default='Science', max_length=18),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Common', 'Common')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('nctb', 'nctb'), ('book', 'book'), ('guide', 'guide'), ('cheradip', 'cheradip')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='types',
            field=models.CharField(choices=[('science', 'science'), ('business', 'business'), ('humanities', 'hamanities'), ('compulsory', 'compulsory'), ('sac', 'sac'), ('ac', 'ac'), ('sc', 'sc')], default='humanities', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=3, unique=True)),
                ('subject_name', models.CharField(blank=True, max_length=50)),
                ('group', models.ManyToManyField(related_name='subjects', to='cheradip.group')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.CharField(blank=True, max_length=2)),
                ('chapter_name', models.CharField(blank=True, max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='cheradip.subject')),
            ],
            options={
                'unique_together': {('subject', 'chapter_no')},
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_no', models.CharField(blank=True, max_length=2)),
                ('subtopic_name', models.CharField(blank=True, max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='cheradip.chapter')),
            ],
            options={
                'unique_together': {('topic', 'subtopic_no')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_no', models.CharField(blank=True, max_length=2)),
                ('topic_name', models.CharField(blank=True, max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='cheradip.chapter')),
            ],
            options={
                'unique_together': {('chapter', 'topic_no')},
            },
        ),
        migrations.CreateModel(
            name='Mcq_ict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uddipok', models.TextField(blank=True, max_length=1000, null=True)),
                ('question', models.TextField(max_length=300)),
                ('option1', models.TextField(max_length=200)),
                ('option2', models.TextField(max_length=200)),
                ('option3', models.TextField(max_length=200)),
                ('option4', models.TextField(max_length=200)),
                ('answer', models.CharField(choices=[('1', 'ক'), ('2', 'খ'), ('3', 'গ'), ('4', 'ঘ')], max_length=1)),
                ('explanation', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cheradip.models.question_image_path)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('board', models.CharField(blank=True, max_length=100, null=True)),
                ('qid', models.CharField(editable=False, max_length=10, unique=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cheradip.chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cheradip.subject')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cheradip.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cheradip.topic')),
            ],
        ),
    ]
