# Generated by Django 5.0.6 on 2024-09-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0002_group_notifications_remove_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='category',
        ),
    ]
