# Generated by Django 5.0.6 on 2024-09-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0002_board_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institute_code', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('institute_name', models.CharField(blank=True, max_length=127, unique=True)),
                ('institute_type', models.CharField(blank=True, max_length=127, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
