# Generated by Django 5.0.6 on 2024-07-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0002_remove_item_category_remove_item_probable_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.CharField(choices=[('science', 'science'), ('business', 'business'), ('humanities', 'humanities')], default='science', max_length=18),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Common', 'Common')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='types',
            field=models.CharField(choices=[('science', 'science'), ('business', 'business'), ('humanities', 'hamanities'), ('compulsory', 'compulsory'), ('sac', 'sac'), ('ac', 'ac'), ('sc', 'sc')], default='humanities', max_length=15, null=True),
        ),
    ]
