# Generated by Django 5.0.6 on 2024-09-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0002_rename_institute_mcq_ict_institutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq_ict',
            old_name='years',
            new_name='year',
        ),
    ]
