# Generated by Django 5.0.6 on 2024-09-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0003_remove_notifications_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
