# Generated by Django 5.0.6 on 2024-09-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0003_rename_years_mcq_ict_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq_ict',
            old_name='year',
            new_name='years',
        ),
    ]
