# Generated by Django 5.0.6 on 2024-09-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0003_institute_delete_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institute_type',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
