# Generated by Django 5.2.5 on 2026-01-25 13:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cheradip', '0004_rename_year_mcq_ict_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banbeis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EIIN', models.BigIntegerField(db_index=True, unique=True)),
                ('Name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('District', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('Thana', models.CharField(blank=True, max_length=255, null=True)),
                ('Rejion', models.CharField(blank=True, max_length=255, null=True)),
                ('PostOffice', models.CharField(blank=True, max_length=127, null=True)),
                ('PostCode', models.CharField(blank=True, max_length=7, null=True)),
                ('WardNo', models.CharField(blank=True, max_length=7, null=True)),
                ('Mouza', models.CharField(blank=True, max_length=127, null=True)),
                ('InstituteType', models.CharField(blank=True, db_index=True, max_length=127, null=True)),
                ('EducationLevels', models.CharField(blank=True, max_length=255, null=True)),
                ('SSCDepts', models.CharField(blank=True, max_length=255, null=True)),
                ('HSCDepts', models.CharField(blank=True, max_length=255, null=True)),
                ('Linked', models.TextField(blank=True, null=True)),
                ('MPO', models.CharField(blank=True, max_length=255, null=True)),
                ('PreStats', models.TextField(blank=True, null=True)),
                ('Record', models.TextField(blank=True, null=True)),
                ('Record2', models.TextField(blank=True, null=True)),
                ('Contact', models.CharField(blank=True, max_length=255, null=True)),
                ('GovtStatus', models.IntegerField(blank=True, choices=[(0, 'Non-Government'), (1, 'Government')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banbeis',
                'ordering': ['EIIN'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(db_index=True, max_length=2, primary_key=True, serialize=False)),
                ('country_code_alpha3', models.CharField(blank=True, max_length=3, null=True)),
                ('country_code_numeric', models.CharField(blank=True, max_length=3, null=True)),
                ('country_name', models.CharField(max_length=60)),
                ('country_name_native', models.CharField(blank=True, max_length=60, null=True)),
                ('country_name_official', models.CharField(blank=True, max_length=100, null=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('flag_url', models.URLField(blank=True, max_length=255, null=True)),
                ('phone_code', models.CharField(max_length=5)),
                ('phone_code_numeric', models.IntegerField(blank=True, null=True)),
                ('phone_format', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_length_min', models.IntegerField(default=10)),
                ('phone_length_max', models.IntegerField(default=10)),
                ('continent', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('capital', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('currency_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('language_codes', models.JSONField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.IntegerField(default=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ['display_order', 'country_name'],
            },
        ),
        migrations.CreateModel(
            name='Institutes',
            fields=[
                ('eiinNo', models.CharField(db_index=True, max_length=15, primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('instituteName', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('instituteNameBn', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('mobileAlternate', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('divisionName', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('divisionNameBn', models.CharField(blank=True, max_length=100, null=True)),
                ('districtName', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('districtNameBn', models.CharField(blank=True, max_length=100, null=True)),
                ('thanaName', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('thanaNameBn', models.CharField(blank=True, max_length=100, null=True)),
                ('mouzaName', models.CharField(blank=True, max_length=255, null=True)),
                ('mouzaNameBn', models.CharField(blank=True, max_length=255, null=True)),
                ('instituteTypeName', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('instituteTypeNameBn', models.CharField(blank=True, max_length=100, null=True)),
                ('isGovt', models.BooleanField(blank=True, default=False, null=True)),
                ('submissionDate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'institutes',
                'ordering': ['eiinNo'],
            },
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.IntegerField(db_index=True)),
                ('Name', models.CharField(db_index=True, max_length=255)),
                ('Batch', models.IntegerField(db_index=True)),
                ('Roll', models.BigIntegerField(db_index=True)),
                ('Mark', models.IntegerField()),
                ('Rank', models.IntegerField()),
                ('SL', models.IntegerField()),
                ('Subject', models.CharField(db_index=True, max_length=127)),
                ('EIIN', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('InstituteName', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'merits',
                'ordering': ['Batch', 'Rank', 'SL'],
            },
        ),
        migrations.CreateModel(
            name='Merit5',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.IntegerField(db_index=True)),
                ('Name', models.CharField(db_index=True, max_length=255)),
                ('Batch', models.IntegerField(db_index=True)),
                ('Roll', models.BigIntegerField(db_index=True)),
                ('Mark', models.IntegerField()),
                ('Rank', models.IntegerField()),
                ('SL', models.IntegerField()),
                ('Subject', models.CharField(db_index=True, max_length=127)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'merits_5',
                'ordering': ['Batch', 'Rank', 'SL'],
            },
        ),
        migrations.CreateModel(
            name='Merit6',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.IntegerField(db_index=True)),
                ('Name', models.CharField(db_index=True, max_length=255)),
                ('Batch', models.IntegerField(db_index=True)),
                ('Roll', models.BigIntegerField(db_index=True)),
                ('Mark', models.IntegerField()),
                ('Rank', models.IntegerField()),
                ('SL', models.IntegerField()),
                ('Subject', models.CharField(db_index=True, max_length=127)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'merits_6',
                'ordering': ['Batch', 'Rank', 'SL'],
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EIIN', models.BigIntegerField(db_index=True)),
                ('District', models.CharField(blank=True, db_index=True, max_length=127, null=True)),
                ('Thana', models.CharField(blank=True, max_length=127, null=True)),
                ('Designation', models.CharField(blank=True, max_length=255, null=True)),
                ('Post', models.CharField(blank=True, max_length=255, null=True)),
                ('Batch', models.CharField(blank=True, max_length=255, null=True)),
                ('Merit', models.CharField(blank=True, max_length=63, null=True)),
                ('Roll', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('Name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('Code', models.IntegerField(blank=True, null=True)),
                ('Mark', models.IntegerField(blank=True, null=True)),
                ('Rank', models.IntegerField(blank=True, null=True)),
                ('Serial', models.IntegerField(blank=True, null=True)),
                ('Subject', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommend5',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EIIN', models.BigIntegerField(db_index=True)),
                ('District', models.CharField(blank=True, max_length=127, null=True)),
                ('Thana', models.CharField(blank=True, max_length=127, null=True)),
                ('Designation', models.CharField(blank=True, max_length=255, null=True)),
                ('Batch', models.CharField(blank=True, max_length=255, null=True)),
                ('Merit', models.CharField(blank=True, max_length=63, null=True)),
                ('Roll', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Code', models.IntegerField(blank=True, null=True)),
                ('Mark', models.IntegerField(blank=True, null=True)),
                ('Rank', models.IntegerField(blank=True, null=True)),
                ('Serial', models.IntegerField(blank=True, null=True)),
                ('Subject', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recommendations_5',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommend6',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EIIN', models.BigIntegerField(db_index=True)),
                ('District', models.CharField(blank=True, max_length=127, null=True)),
                ('Thana', models.CharField(blank=True, max_length=127, null=True)),
                ('Designation', models.CharField(blank=True, max_length=255, null=True)),
                ('Batch', models.CharField(blank=True, max_length=255, null=True)),
                ('Merit', models.CharField(blank=True, max_length=63, null=True)),
                ('Roll', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Code', models.IntegerField(blank=True, null=True)),
                ('Mark', models.IntegerField(blank=True, null=True)),
                ('Rank', models.IntegerField(blank=True, null=True)),
                ('Serial', models.IntegerField(blank=True, null=True)),
                ('Subject', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recommendations_6',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Token', models.BigIntegerField(db_index=True, unique=True)),
                ('Counter', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.IntegerField(blank=True, choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Used'), (3, 'Expired')], default=1, null=True)),
                ('purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('VPID', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('EIIN', models.BigIntegerField(db_index=True)),
                ('Name', models.CharField(db_index=True, max_length=255)),
                ('District', models.CharField(db_index=True, max_length=255)),
                ('Thana', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=255)),
                ('Vacancy', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('Type', models.CharField(choices=[('regular', 'Regular'), ('temporary', 'Temporary'), ('contract', 'Contract')], default='regular', max_length=15)),
                ('Status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], default='open', max_length=31)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vacancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy5',
            fields=[
                ('VPID', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('EIIN', models.BigIntegerField(db_index=True)),
                ('Name', models.CharField(db_index=True, max_length=255)),
                ('District', models.CharField(db_index=True, max_length=255)),
                ('Thana', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=255)),
                ('Vacancy', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('Type', models.CharField(choices=[('regular', 'Regular'), ('temporary', 'Temporary'), ('contract', 'Contract')], default='regular', max_length=15)),
                ('Status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], default='open', max_length=31)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vacancies_5',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy6',
            fields=[
                ('VPID', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('EIIN', models.BigIntegerField(db_index=True)),
                ('Name', models.CharField(db_index=True, max_length=255)),
                ('District', models.CharField(db_index=True, max_length=255)),
                ('Thana', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=255)),
                ('Vacancy', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('Type', models.CharField(choices=[('regular', 'Regular'), ('temporary', 'Temporary'), ('contract', 'Contract')], default='regular', max_length=15)),
                ('Status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], default='open', max_length=31)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vacancies_6',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='canceled',
            options={'ordering': ['-cancelled_at']},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['subject', 'chapter_no']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterModelOptions(
            name='customertoken',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['group_code']},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'ordering': ['institute_name']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jsondata',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mcq_ict',
            options={'ordering': ['subject', 'chapter', 'topic', 'qid']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'ordering': ['SN']},
        ),
        migrations.AlterModelOptions(
            name='ordered',
            options={'ordering': ['-delivered_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_code']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['chapter', 'topic_no']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-year_code']},
        ),
        migrations.RemoveField(
            model_name='canceled',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='ordered',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='group',
        ),
        migrations.AddField(
            model_name='canceled',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canceled',
            name='cancelled_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='canceled',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='canceled',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canceled',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='cancelled_orders', to='cheradip.transaction'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='class_name',
            field=models.CharField(blank=True, choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_alternate',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='verification_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_apikey',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='group_name_bn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institute',
            name='institute_name_bn',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jsondata',
            name='data_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mcq_ict',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq_ict',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mcq_ict',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mcq_ict',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'High'), (2, 'Urgent')], default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='orders', to='cheradip.transaction'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordered',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordered',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordered',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordered',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered')], default='delivered', max_length=20),
        ),
        migrations.AddField(
            model_name='ordered',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='ordered_items', to='cheradip.transaction'),
        ),
        migrations.AddField(
            model_name='ordered',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(db_table='subject_groups', related_name='subjects', to='cheradip.group'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_name_bn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('dbbl', 'DBBL'), ('rocket', 'Rocket'), ('cash', 'Cash')], default='bkash', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='year',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='year',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='year',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='year',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='year',
            name='year_name_bn',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='canceled',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='canceled',
            name='orderDetails',
            field=models.ManyToManyField(blank=True, related_name='cancelled_orders', to='cheradip.orderdetail'),
        ),
        migrations.AlterField(
            model_name='canceled',
            name='paymentMethod',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('dbbl', 'DBBL'), ('other', 'Other')], max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='canceled',
            name='username',
            field=models.CharField(db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_no',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='village',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customertoken',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='customertoken',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_code',
            field=models.CharField(db_index=True, max_length=1, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institute_code',
            field=models.CharField(db_index=True, max_length=14, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='add_to_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='bangla_name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='in_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='love',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('dbbl', 'DBBL'), ('other', 'Other')], default='bkash', max_length=28),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='reviews',
            field=models.TextField(blank=True, default='Rated By @Author', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='shipping',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('nctb', 'NCTB'), ('book', 'Book'), ('guide', 'Guide'), ('cheradip', 'Cheradip')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='types',
            field=models.CharField(choices=[('science', 'Science'), ('business', 'Business'), ('humanities', 'Humanities'), ('compulsory', 'Compulsory'), ('sac', 'SAC'), ('ac', 'AC'), ('sc', 'SC')], default='humanities', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mcq_ict',
            name='institutes',
            field=models.ManyToManyField(blank=True, db_table='mcq_institutes', related_name='questions', to='cheradip.institute'),
        ),
        migrations.AlterField(
            model_name='mcq_ict',
            name='qid',
            field=models.CharField(db_index=True, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq_ict',
            name='uddipok',
            field=models.TextField(blank=True, help_text='Question context/hint', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mcq_ict',
            name='years',
            field=models.ManyToManyField(blank=True, db_table='mcq_years', related_name='questions', to='cheradip.year'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDetails',
            field=models.ManyToManyField(blank=True, related_name='orders', to='cheradip.orderdetail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('dbbl', 'DBBL'), ('other', 'Other')], max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Due',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='GrandTotal',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Paid',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='SN',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='ShipingCost',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='Weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_details', to='cheradip.item'),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='orderDetails',
            field=models.ManyToManyField(blank=True, related_name='ordered_items', to='cheradip.orderdetail'),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='paymentMethod',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('dbbl', 'DBBL'), ('other', 'Other')], max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='shipped',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ordered',
            name='username',
            field=models.CharField(db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(db_index=True, max_length=3, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_no',
            field=models.CharField(blank=True, db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Paid',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paidFrom',
            field=models.CharField(blank=True, default='', max_length=31),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trxid',
            field=models.CharField(db_index=True, max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='year_code',
            field=models.CharField(db_index=True, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='canceled',
            index=models.Index(fields=['username'], name='canceled_usernam_c39997_idx'),
        ),
        migrations.AddIndex(
            model_name='canceled',
            index=models.Index(fields=['customer', 'cancelled_at'], name='canceled_custome_470d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['subject', 'chapter_no'], name='chapters_subject_0d3afb_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['username'], name='customers_usernam_fad06d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_email_92e882_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['acctype'], name='customers_acctype_57964f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['division', 'district'], name='customers_divisio_2540aa_idx'),
        ),
        migrations.AddIndex(
            model_name='customertoken',
            index=models.Index(fields=['key'], name='customer_to_key_9b28f5_idx'),
        ),
        migrations.AddIndex(
            model_name='customertoken',
            index=models.Index(fields=['customer', 'created'], name='customer_to_custome_f622a5_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['group_code'], name='groups_group_c_149b33_idx'),
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['institute_code'], name='institute_t_institu_f8f976_idx'),
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['institute_name'], name='institute_t_institu_b33118_idx'),
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['institute_type'], name='institute_t_institu_98f258_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['code'], name='items_code_47e090_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['types'], name='items_types_fbd683_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='items_name_dd4454_idx'),
        ),
        migrations.AddIndex(
            model_name='jsondata',
            index=models.Index(fields=['data_type'], name='json_data_data_ty_66e340_idx'),
        ),
        migrations.AddIndex(
            model_name='jsondata',
            index=models.Index(fields=['created_at'], name='json_data_created_48c7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='mcq_ict',
            index=models.Index(fields=['qid'], name='mcq_ict_qid_2e21ce_idx'),
        ),
        migrations.AddIndex(
            model_name='mcq_ict',
            index=models.Index(fields=['subject', 'chapter', 'topic'], name='mcq_ict_subject_09e63e_idx'),
        ),
        migrations.AddIndex(
            model_name='mcq_ict',
            index=models.Index(fields=['is_active'], name='mcq_ict_is_acti_dabbe7_idx'),
        ),
        migrations.AddIndex(
            model_name='mcq_ict',
            index=models.Index(fields=['difficulty_level'], name='mcq_ict_difficu_e77fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_active', 'priority'], name='notificatio_is_acti_032af9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['username'], name='orders_usernam_9b66d0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'created_at'], name='orders_custome_18fe5d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['item'], name='order_detai_item_id_d9ba3b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordered',
            index=models.Index(fields=['username'], name='ordered_usernam_2d14e8_idx'),
        ),
        migrations.AddIndex(
            model_name='ordered',
            index=models.Index(fields=['status'], name='ordered_status_38eda7_idx'),
        ),
        migrations.AddIndex(
            model_name='ordered',
            index=models.Index(fields=['customer', 'delivered_at'], name='ordered_custome_6b5b84_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_code'], name='subjects_subject_e16b01_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['chapter', 'topic_no'], name='topics_chapter_5a7c61_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['trxid'], name='transaction_trxid_78c39c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['username'], name='transaction_usernam_ee0e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='transaction_status_94cf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='year',
            index=models.Index(fields=['year_code'], name='years_year_co_ddc639_idx'),
        ),
        migrations.AlterModelTable(
            name='canceled',
            table='canceled',
        ),
        migrations.AlterModelTable(
            name='chapter',
            table='chapters',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='customertoken',
            table='customer_tokens',
        ),
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
        migrations.AlterModelTable(
            name='institute',
            table='institute_types',
        ),
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
        migrations.AlterModelTable(
            name='jsondata',
            table='json_data',
        ),
        migrations.AlterModelTable(
            name='mcq_ict',
            table='mcq_ict',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table='order_details',
        ),
        migrations.AlterModelTable(
            name='ordered',
            table='ordered',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subjects',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
        migrations.AlterModelTable(
            name='year',
            table='years',
        ),
        migrations.AddIndex(
            model_name='banbeis',
            index=models.Index(fields=['EIIN'], name='banbeis_EIIN_cf994f_idx'),
        ),
        migrations.AddIndex(
            model_name='banbeis',
            index=models.Index(fields=['Name'], name='banbeis_Name_ae6326_idx'),
        ),
        migrations.AddIndex(
            model_name='banbeis',
            index=models.Index(fields=['District', 'Thana'], name='banbeis_Distric_142f65_idx'),
        ),
        migrations.AddIndex(
            model_name='banbeis',
            index=models.Index(fields=['InstituteType'], name='banbeis_Institu_92225d_idx'),
        ),
        migrations.AddIndex(
            model_name='banbeis',
            index=models.Index(fields=['GovtStatus'], name='banbeis_GovtSta_36e160_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['country_code'], name='countries_country_f87cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['country_name'], name='countries_country_6f41c3_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['phone_code'], name='countries_phone_c_f4d3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['is_featured', 'display_order'], name='countries_is_feat_712368_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['continent'], name='countries_contine_04b12f_idx'),
        ),
        migrations.AddIndex(
            model_name='institutes',
            index=models.Index(fields=['eiinNo'], name='institutes_eiinNo_84e2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='institutes',
            index=models.Index(fields=['instituteName'], name='institutes_institu_bf8fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='institutes',
            index=models.Index(fields=['divisionName', 'districtName', 'thanaName'], name='institutes_divisio_0b1488_idx'),
        ),
        migrations.AddIndex(
            model_name='institutes',
            index=models.Index(fields=['instituteTypeName'], name='institutes_institu_d1816a_idx'),
        ),
        migrations.AddIndex(
            model_name='institutes',
            index=models.Index(fields=['isGovt'], name='institutes_isGovt_2fdb78_idx'),
        ),
        migrations.AddIndex(
            model_name='merit',
            index=models.Index(fields=['Code'], name='merits_Code_9277ee_idx'),
        ),
        migrations.AddIndex(
            model_name='merit',
            index=models.Index(fields=['Batch', 'Rank'], name='merits_Batch_c84297_idx'),
        ),
        migrations.AddIndex(
            model_name='merit',
            index=models.Index(fields=['Roll'], name='merits_Roll_17466b_idx'),
        ),
        migrations.AddIndex(
            model_name='merit',
            index=models.Index(fields=['Subject', 'Rank'], name='merits_Subject_52c3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='merit',
            index=models.Index(fields=['EIIN'], name='merits_EIIN_8b1d46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='merit',
            unique_together={('Batch', 'Roll', 'Subject')},
        ),
        migrations.AddIndex(
            model_name='merit5',
            index=models.Index(fields=['Batch', 'Rank'], name='merits_5_Batch_ef13ec_idx'),
        ),
        migrations.AddIndex(
            model_name='merit5',
            index=models.Index(fields=['Roll'], name='merits_5_Roll_6cfc22_idx'),
        ),
        migrations.AddIndex(
            model_name='merit5',
            index=models.Index(fields=['Subject'], name='merits_5_Subject_ea49e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='merit5',
            unique_together={('Batch', 'Roll', 'Subject')},
        ),
        migrations.AddIndex(
            model_name='merit6',
            index=models.Index(fields=['Batch', 'Rank'], name='merits_6_Batch_2b709a_idx'),
        ),
        migrations.AddIndex(
            model_name='merit6',
            index=models.Index(fields=['Roll'], name='merits_6_Roll_9e7c63_idx'),
        ),
        migrations.AddIndex(
            model_name='merit6',
            index=models.Index(fields=['Subject'], name='merits_6_Subject_5e12b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='merit6',
            unique_together={('Batch', 'Roll', 'Subject')},
        ),
        migrations.AddIndex(
            model_name='recommend',
            index=models.Index(fields=['EIIN'], name='recommendat_EIIN_5f8ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='recommend',
            index=models.Index(fields=['Roll'], name='recommendat_Roll_9943c2_idx'),
        ),
        migrations.AddIndex(
            model_name='recommend',
            index=models.Index(fields=['Name'], name='recommendat_Name_55a0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='recommend',
            index=models.Index(fields=['Subject', 'Rank'], name='recommendat_Subject_dd8c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='recommend',
            index=models.Index(fields=['status'], name='recommendat_status_88bbb1_idx'),
        ),
        migrations.AddIndex(
            model_name='recommend5',
            index=models.Index(fields=['EIIN', 'Roll'], name='recommendat_EIIN_e28436_idx'),
        ),
        migrations.AddIndex(
            model_name='recommend5',
            index=models.Index(fields=['Subject'], name='recommendat_Subject_ea02c8_idx'),
        ),
        migrations.AddIndex(
            model_name='recommend6',
            index=models.Index(fields=['EIIN', 'Roll'], name='recommendat_EIIN_c0a574_idx'),
        ),
        migrations.AddIndex(
            model_name='recommend6',
            index=models.Index(fields=['Subject'], name='recommendat_Subject_86ceef_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['Token'], name='tokens_Token_486bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['Status'], name='tokens_Status_83f054_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['purpose'], name='tokens_purpose_ea833d_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['VPID'], name='vacancies_VPID_4f0c92_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['EIIN'], name='vacancies_EIIN_28022b_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['Status', 'Type'], name='vacancies_Status_c960ee_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['District', 'Thana'], name='vacancies_Distric_3168e4_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['Subject'], name='vacancies_Subject_977dde_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy5',
            index=models.Index(fields=['VPID'], name='vacancies_5_VPID_939738_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy5',
            index=models.Index(fields=['EIIN'], name='vacancies_5_EIIN_99e1d3_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy5',
            index=models.Index(fields=['Status'], name='vacancies_5_Status_f70d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy5',
            index=models.Index(fields=['District', 'Subject'], name='vacancies_5_Distric_a96db8_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy6',
            index=models.Index(fields=['VPID'], name='vacancies_6_VPID_875d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy6',
            index=models.Index(fields=['EIIN'], name='vacancies_6_EIIN_3c7632_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy6',
            index=models.Index(fields=['Status'], name='vacancies_6_Status_b9fa8b_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy6',
            index=models.Index(fields=['District', 'Subject'], name='vacancies_6_Distric_1749b6_idx'),
        ),
    ]
