# Generated by Django 5.0.6 on 2024-09-13 19:08

import cheradip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0004_alter_institute_institute_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq_ict',
            old_name='image',
            new_name='img_explanation',
        ),
        migrations.RemoveField(
            model_name='mcq_ict',
            name='board',
        ),
        migrations.RemoveField(
            model_name='mcq_ict',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mcq_ict',
            name='year',
        ),
        migrations.AddField(
            model_name='mcq_ict',
            name='img_question',
            field=models.ImageField(blank=True, null=True, upload_to=cheradip.models.question_image_path),
        ),
        migrations.AddField(
            model_name='mcq_ict',
            name='img_uddipok',
            field=models.ImageField(blank=True, null=True, upload_to=cheradip.models.question_image_path),
        ),
        migrations.AddField(
            model_name='mcq_ict',
            name='institutes',
            field=models.ManyToManyField(related_name='questions', to='cheradip.institute'),
        ),
        migrations.AddField(
            model_name='mcq_ict',
            name='years',
            field=models.ManyToManyField(related_name='questions', to='cheradip.year'),
        ),
        migrations.AlterField(
            model_name='mcq_ict',
            name='qid',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
