# Generated by Django 5.2.5 on 2026-01-27 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0005_banbeis_country_institutes_merit_merit5_merit6_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('class_code', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('class_name', models.CharField(max_length=50)),
                ('class_name_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_groups', models.BooleanField(default=False)),
                ('has_departments', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'class_levels',
                'ordering': ['display_order', 'class_code'],
                'indexes': [models.Index(fields=['class_code'], name='class_level_class_c_50f58e_idx'), models.Index(fields=['has_groups', 'has_departments'], name='class_level_has_gro_4742c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_code', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('dept_name_short', models.CharField(blank=True, max_length=20, null=True)),
                ('faculty', models.CharField(blank=True, help_text='Faculty name (e.g., Engineering, Arts)', max_length=100, null=True)),
                ('faculty_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('degree_type', models.CharField(blank=True, help_text='e.g., BSc, BA, BBA, MBBS', max_length=50, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['display_order', 'dept_name'],
                'indexes': [models.Index(fields=['dept_code'], name='departments_dept_co_6e9cac_idx'), models.Index(fields=['faculty'], name='departments_faculty_d444ca_idx'), models.Index(fields=['is_active', 'display_order'], name='departments_is_acti_9cfa61_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_codes', models.CharField(help_text='Comma-separated group codes (e.g., S,A,B)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mappings', to='cheradip.classlevel')),
            ],
            options={
                'db_table': 'class_group_mappings',
                'indexes': [models.Index(fields=['class_level'], name='class_group_class_l_571a5c_idx')],
                'unique_together': {('class_level', 'group_codes')},
            },
        ),
    ]
