# Generated by Django 5.0.6 on 2024-07-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0005_alter_customer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
        migrations.AddField(
            model_name='customer',
            name='acctype',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=7),
        ),
    ]
