# Generated by Django 5.2.5 on 2026-01-27 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0006_classlevel_department_classgroupmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_name', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('division_name_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('division_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'divisions',
                'ordering': ['display_order', 'division_name'],
                'indexes': [models.Index(fields=['division_name'], name='divisions_divisio_0238a2_idx'), models.Index(fields=['is_active', 'display_order'], name='divisions_is_acti_fb3b5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(db_index=True, max_length=50)),
                ('district_name_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('district_code', models.CharField(blank=True, max_length=10, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='cheradip.division')),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['division', 'display_order', 'district_name'],
            },
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thana_name', models.CharField(db_index=True, max_length=100)),
                ('thana_name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('thana_code', models.CharField(blank=True, max_length=10, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanas', to='cheradip.district')),
            ],
            options={
                'db_table': 'thanas',
                'ordering': ['district', 'display_order', 'thana_name'],
            },
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['division', 'district_name'], name='districts_divisio_9fd03f_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['district_name'], name='districts_distric_fb3bee_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['is_active'], name='districts_is_acti_a43f13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('division', 'district_name')},
        ),
        migrations.AddIndex(
            model_name='thana',
            index=models.Index(fields=['district', 'thana_name'], name='thanas_distric_12070f_idx'),
        ),
        migrations.AddIndex(
            model_name='thana',
            index=models.Index(fields=['thana_name'], name='thanas_thana_n_0dc636_idx'),
        ),
        migrations.AddIndex(
            model_name='thana',
            index=models.Index(fields=['is_active'], name='thanas_is_acti_fa8afd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thana',
            unique_together={('district', 'thana_name')},
        ),
    ]
