# Generated by Django 5.2.5 on 2026-04-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0006_trxmanagement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='createdquestionset',
            new_name='cheradip_cr_custome_c6810a_idx',
            old_name='cqs_customer_counter_idx',
        ),
        migrations.AlterField(
            model_name='createdquestionset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pendingquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
