# Generated by Django 5.0.6 on 2024-07-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0007_alter_customer_acctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='acctype',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=7),
        ),
    ]
