# Generated by Django 5.2.5 on 2026-01-27 03:59

from django.db import migrations, models


def rename_tables(apps, schema_editor):
    """Rename all tables to add cheradip_ prefix. Supports MySQL and SQLite."""
    conn = schema_editor.connection
    table_renames = {
        'banbeis': 'cheradip_banbeis',
        'canceled': 'cheradip_canceled',
        'chapters': 'cheradip_chapters',
        'class_group_mappings': 'cheradip_class_group_mappings',
        'class_levels': 'cheradip_class_levels',
        'countries': 'cheradip_countries',
        'customers': 'cheradip_customers',
        'customer_tokens': 'cheradip_customer_tokens',
        'departments': 'cheradip_departments',
        'districts': 'cheradip_districts',
        'divisions': 'cheradip_divisions',
        'groups': 'cheradip_groups',
        'institute_types': 'cheradip_institute_types',
        'institutes': 'cheradip_institutes',
        'items': 'cheradip_items',
        'json_data': 'cheradip_json_data',
        'mcq_ict': 'cheradip_mcq_ict',
        'merits': 'cheradip_merits',
        'merits_5': 'cheradip_merits_5',
        'merits_6': 'cheradip_merits_6',
        'notifications': 'cheradip_notifications',
        'orders': 'cheradip_orders',
        'order_details': 'cheradip_order_details',
        'ordered': 'cheradip_ordered',
        'recommendations': 'cheradip_recommendations',
        'recommendations_5': 'cheradip_recommendations_5',
        'recommendations_6': 'cheradip_recommendations_6',
        'subjects': 'cheradip_subjects',
        'thanas': 'cheradip_thanas',
        'tokens': 'cheradip_tokens',
        'topics': 'cheradip_topics',
        'transactions': 'cheradip_transactions',
        'vacancies': 'cheradip_vacancies',
        'vacancies_5': 'cheradip_vacancies_5',
        'vacancies_6': 'cheradip_vacancies_6',
        'years': 'cheradip_years',
        'subject_groups': 'cheradip_subject_groups',
        'mcq_institutes': 'cheradip_mcq_institutes',
        'mcq_years': 'cheradip_mcq_years',
    }
    with conn.cursor() as cursor:
        if conn.vendor == 'sqlite':
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
            existing_tables = [row[0] for row in cursor.fetchall()]
            for old_name, new_name in table_renames.items():
                try:
                    if old_name in existing_tables and new_name not in existing_tables:
                        cursor.execute(f'ALTER TABLE "{old_name}" RENAME TO "{new_name}"')
                        existing_tables.remove(old_name)
                        existing_tables.append(new_name)
                except Exception as e:
                    pass  # skip on error
        else:
            cursor.execute("SHOW TABLES")
            existing_tables = [row[0] for row in cursor.fetchall()]
            for old_name, new_name in table_renames.items():
                try:
                    if old_name in existing_tables and new_name not in existing_tables:
                        cursor.execute(f"RENAME TABLE `{old_name}` TO `{new_name}`")
                except Exception as e:
                    pass


def reverse_rename_tables(apps, schema_editor):
    """Reverse the table renames. Supports MySQL and SQLite."""
    conn = schema_editor.connection
    table_renames = {
        'cheradip_banbeis': 'banbeis',
        'cheradip_canceled': 'canceled',
        'cheradip_chapters': 'chapters',
        'cheradip_class_group_mappings': 'class_group_mappings',
        'cheradip_class_levels': 'class_levels',
        'cheradip_countries': 'countries',
        'cheradip_customers': 'customers',
        'cheradip_customer_tokens': 'customer_tokens',
        'cheradip_departments': 'departments',
        'cheradip_districts': 'districts',
        'cheradip_divisions': 'divisions',
        'cheradip_groups': 'groups',
        'cheradip_institute_types': 'institute_types',
        'cheradip_institutes': 'institutes',
        'cheradip_items': 'items',
        'cheradip_json_data': 'json_data',
        'cheradip_mcq_ict': 'mcq_ict',
        'cheradip_merits': 'merits',
        'cheradip_merits_5': 'merits_5',
        'cheradip_merits_6': 'merits_6',
        'cheradip_notifications': 'notifications',
        'cheradip_orders': 'orders',
        'cheradip_order_details': 'order_details',
        'cheradip_ordered': 'ordered',
        'cheradip_recommendations': 'recommendations',
        'cheradip_recommendations_5': 'recommendations_5',
        'cheradip_recommendations_6': 'recommendations_6',
        'cheradip_subjects': 'subjects',
        'cheradip_thanas': 'thanas',
        'cheradip_tokens': 'tokens',
        'cheradip_topics': 'topics',
        'cheradip_transactions': 'transactions',
        'cheradip_vacancies': 'vacancies',
        'cheradip_vacancies_5': 'vacancies_5',
        'cheradip_vacancies_6': 'vacancies_6',
        'cheradip_years': 'years',
        'cheradip_subject_groups': 'subject_groups',
        'cheradip_mcq_institutes': 'mcq_institutes',
        'cheradip_mcq_years': 'mcq_years',
    }
    with conn.cursor() as cursor:
        if conn.vendor == 'sqlite':
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
            existing_tables = [row[0] for row in cursor.fetchall()]
            for old_name, new_name in table_renames.items():
                try:
                    if old_name in existing_tables:
                        cursor.execute(f'ALTER TABLE "{old_name}" RENAME TO "{new_name}"')
                        existing_tables.remove(old_name)
                        existing_tables.append(new_name)
                except Exception as e:
                    pass
        else:
            cursor.execute("SHOW TABLES")
            existing_tables = [row[0] for row in cursor.fetchall()]
            for old_name, new_name in table_renames.items():
                try:
                    if old_name in existing_tables:
                        cursor.execute(f"RENAME TABLE `{old_name}` TO `{new_name}`")
                except Exception as e:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0007_division_district_thana_and_more'),
    ]

    operations = [
        # Rename all tables in database first
        migrations.RunPython(rename_tables, reverse_rename_tables),
        # Update Django's model state (state-only, no database operations)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='mcq_ict',
                    name='institutes',
                    field=models.ManyToManyField(blank=True, db_table='cheradip_mcq_institutes', related_name='questions', to='cheradip.institute'),
                ),
                migrations.AlterField(
                    model_name='mcq_ict',
                    name='years',
                    field=models.ManyToManyField(blank=True, db_table='cheradip_mcq_years', related_name='questions', to='cheradip.year'),
                ),
                migrations.AlterField(
                    model_name='subject',
                    name='groups',
                    field=models.ManyToManyField(db_table='cheradip_subject_groups', related_name='subjects', to='cheradip.group'),
                ),
                migrations.AlterModelTable(
                    name='banbeis',
                    table='cheradip_banbeis',
                ),
                migrations.AlterModelTable(
                    name='canceled',
                    table='cheradip_canceled',
                ),
                migrations.AlterModelTable(
                    name='chapter',
                    table='cheradip_chapters',
                ),
                migrations.AlterModelTable(
                    name='classgroupmapping',
                    table='cheradip_class_group_mappings',
                ),
                migrations.AlterModelTable(
                    name='classlevel',
                    table='cheradip_class_levels',
                ),
                migrations.AlterModelTable(
                    name='country',
                    table='cheradip_countries',
                ),
                migrations.AlterModelTable(
                    name='customer',
                    table='cheradip_customers',
                ),
                migrations.AlterModelTable(
                    name='customertoken',
                    table='cheradip_customer_tokens',
                ),
                migrations.AlterModelTable(
                    name='department',
                    table='cheradip_departments',
                ),
                migrations.AlterModelTable(
                    name='district',
                    table='cheradip_districts',
                ),
                migrations.AlterModelTable(
                    name='division',
                    table='cheradip_divisions',
                ),
                migrations.AlterModelTable(
                    name='group',
                    table='cheradip_groups',
                ),
                migrations.AlterModelTable(
                    name='institute',
                    table='cheradip_institute_types',
                ),
                migrations.AlterModelTable(
                    name='institutes',
                    table='cheradip_institutes',
                ),
                migrations.AlterModelTable(
                    name='item',
                    table='cheradip_items',
                ),
                migrations.AlterModelTable(
                    name='jsondata',
                    table='cheradip_json_data',
                ),
                migrations.AlterModelTable(
                    name='mcq_ict',
                    table='cheradip_mcq_ict',
                ),
                migrations.AlterModelTable(
                    name='merit',
                    table='cheradip_merits',
                ),
                migrations.AlterModelTable(
                    name='merit5',
                    table='cheradip_merits_5',
                ),
                migrations.AlterModelTable(
                    name='merit6',
                    table='cheradip_merits_6',
                ),
                migrations.AlterModelTable(
                    name='notification',
                    table='cheradip_notifications',
                ),
                migrations.AlterModelTable(
                    name='order',
                    table='cheradip_orders',
                ),
                migrations.AlterModelTable(
                    name='orderdetail',
                    table='cheradip_order_details',
                ),
                migrations.AlterModelTable(
                    name='ordered',
                    table='cheradip_ordered',
                ),
                migrations.AlterModelTable(
                    name='recommend',
                    table='cheradip_recommendations',
                ),
                migrations.AlterModelTable(
                    name='recommend5',
                    table='cheradip_recommendations_5',
                ),
                migrations.AlterModelTable(
                    name='recommend6',
                    table='cheradip_recommendations_6',
                ),
                migrations.AlterModelTable(
                    name='subject',
                    table='cheradip_subjects',
                ),
                migrations.AlterModelTable(
                    name='thana',
                    table='cheradip_thanas',
                ),
                migrations.AlterModelTable(
                    name='token',
                    table='cheradip_tokens',
                ),
                migrations.AlterModelTable(
                    name='topic',
                    table='cheradip_topics',
                ),
                migrations.AlterModelTable(
                    name='transaction',
                    table='cheradip_transactions',
                ),
                migrations.AlterModelTable(
                    name='vacancy',
                    table='cheradip_vacancies',
                ),
                migrations.AlterModelTable(
                    name='vacancy5',
                    table='cheradip_vacancies_5',
                ),
                migrations.AlterModelTable(
                    name='vacancy6',
                    table='cheradip_vacancies_6',
                ),
                migrations.AlterModelTable(
                    name='year',
                    table='cheradip_years',
                ),
            ],
        ),
    ]
