# Generated by Django 5.2.5 on 2026-01-27 04:07
# Modified: use conditional index renames so migration succeeds when old index names don't exist

from django.db import migrations
from django.db.utils import OperationalError


# All RenameIndex operations as (model_name, old_name, new_name)
INDEX_RENAMES = [
    ('banbeis', 'banbeis_EIIN_cf994f_idx', 'cheradip_ba_EIIN_d0c2a3_idx'),
    ('banbeis', 'banbeis_Name_ae6326_idx', 'cheradip_ba_Name_886a09_idx'),
    ('banbeis', 'banbeis_Distric_142f65_idx', 'cheradip_ba_Distric_6f2fab_idx'),
    ('banbeis', 'banbeis_Institu_92225d_idx', 'cheradip_ba_Institu_5e3198_idx'),
    ('banbeis', 'banbeis_GovtSta_36e160_idx', 'cheradip_ba_GovtSta_db5599_idx'),
    ('canceled', 'canceled_usernam_c39997_idx', 'cheradip_ca_usernam_24afde_idx'),
    ('canceled', 'canceled_custome_470d8a_idx', 'cheradip_ca_custome_2441f4_idx'),
    ('chapter', 'chapters_subject_0d3afb_idx', 'cheradip_ch_subject_3cbb00_idx'),
    ('classgroupmapping', 'class_group_class_l_571a5c_idx', 'cheradip_cl_class_l_96ac6d_idx'),
    ('classlevel', 'class_level_class_c_50f58e_idx', 'cheradip_cl_class_c_fd4ff4_idx'),
    ('classlevel', 'class_level_has_gro_4742c8_idx', 'cheradip_cl_has_gro_59ed84_idx'),
    ('country', 'countries_country_f87cbc_idx', 'cheradip_co_country_3ddee6_idx'),
    ('country', 'countries_country_6f41c3_idx', 'cheradip_co_country_629d23_idx'),
    ('country', 'countries_phone_c_f4d3ec_idx', 'cheradip_co_phone_c_281f4b_idx'),
    ('country', 'countries_is_feat_712368_idx', 'cheradip_co_is_feat_93e83b_idx'),
    ('country', 'countries_contine_04b12f_idx', 'cheradip_co_contine_205e8d_idx'),
    ('customer', 'customers_usernam_fad06d_idx', 'cheradip_cu_usernam_ae7fed_idx'),
    ('customer', 'customers_email_92e882_idx', 'cheradip_cu_email_feaf04_idx'),
    ('customer', 'customers_acctype_57964f_idx', 'cheradip_cu_acctype_1a9516_idx'),
    ('customer', 'customers_divisio_2540aa_idx', 'cheradip_cu_divisio_37b78d_idx'),
    ('customertoken', 'customer_to_key_9b28f5_idx', 'cheradip_cu_key_38fa62_idx'),
    ('customertoken', 'customer_to_custome_f622a5_idx', 'cheradip_cu_custome_7f31f0_idx'),
    ('department', 'departments_dept_co_6e9cac_idx', 'cheradip_de_dept_co_38edba_idx'),
    ('department', 'departments_faculty_d444ca_idx', 'cheradip_de_faculty_6c8086_idx'),
    ('department', 'departments_is_acti_9cfa61_idx', 'cheradip_de_is_acti_3b3b38_idx'),
    ('district', 'districts_divisio_9fd03f_idx', 'cheradip_di_divisio_a0f794_idx'),
    ('district', 'districts_distric_fb3bee_idx', 'cheradip_di_distric_25e383_idx'),
    ('district', 'districts_is_acti_a43f13_idx', 'cheradip_di_is_acti_09c15e_idx'),
    ('division', 'divisions_divisio_0238a2_idx', 'cheradip_di_divisio_fdfcb3_idx'),
    ('division', 'divisions_is_acti_fb3b5b_idx', 'cheradip_di_is_acti_c5f944_idx'),
    ('group', 'groups_group_c_149b33_idx', 'cheradip_gr_group_c_656810_idx'),
    ('institute', 'institute_t_institu_f8f976_idx', 'cheradip_in_institu_da8ab5_idx'),
    ('institute', 'institute_t_institu_b33118_idx', 'cheradip_in_institu_f8659a_idx'),
    ('institute', 'institute_t_institu_98f258_idx', 'cheradip_in_institu_18d124_idx'),
    ('institutes', 'institutes_eiinNo_84e2dd_idx', 'cheradip_in_eiinNo_83a2e5_idx'),
    ('institutes', 'institutes_institu_bf8fe9_idx', 'cheradip_in_institu_64068a_idx'),
    ('institutes', 'institutes_divisio_0b1488_idx', 'cheradip_in_divisio_910efd_idx'),
    ('institutes', 'institutes_institu_d1816a_idx', 'cheradip_in_institu_e79874_idx'),
    ('institutes', 'institutes_isGovt_2fdb78_idx', 'cheradip_in_isGovt_d0c966_idx'),
    ('item', 'items_code_47e090_idx', 'cheradip_it_code_81532a_idx'),
    ('item', 'items_types_fbd683_idx', 'cheradip_it_types_cc2590_idx'),
    ('item', 'items_name_dd4454_idx', 'cheradip_it_name_5fc92f_idx'),
    ('jsondata', 'json_data_data_ty_66e340_idx', 'cheradip_js_data_ty_eda6ca_idx'),
    ('jsondata', 'json_data_created_48c7ad_idx', 'cheradip_js_created_7c5b22_idx'),
    ('mcq_ict', 'mcq_ict_qid_2e21ce_idx', 'cheradip_mc_qid_6d8079_idx'),
    ('mcq_ict', 'mcq_ict_subject_09e63e_idx', 'cheradip_mc_subject_3c1286_idx'),
    ('mcq_ict', 'mcq_ict_is_acti_dabbe7_idx', 'cheradip_mc_is_acti_0cf0bf_idx'),
    ('mcq_ict', 'mcq_ict_difficu_e77fe1_idx', 'cheradip_mc_difficu_247977_idx'),
    ('merit', 'merits_Code_9277ee_idx', 'cheradip_me_Code_37cbd5_idx'),
    ('merit', 'merits_Batch_c84297_idx', 'cheradip_me_Batch_c8cde6_idx'),
    ('merit', 'merits_Roll_1746b6_idx', 'cheradip_me_Roll_febd7f_idx'),
    ('merit', 'merits_Subject_52c3e8_idx', 'cheradip_me_Subject_9729dd_idx'),
    ('merit', 'merits_EIIN_8b1d46_idx', 'cheradip_me_EIIN_9969c6_idx'),
    ('merit5', 'merits_5_Batch_ef13ec_idx', 'cheradip_me_Batch_46cf85_idx'),
    ('merit5', 'merits_5_Roll_6cfc22_idx', 'cheradip_me_Roll_8759a9_idx'),
    ('merit5', 'merits_5_Subject_ea49e1_idx', 'cheradip_me_Subject_ee54a6_idx'),
    ('merit6', 'merits_6_Batch_2b709a_idx', 'cheradip_me_Batch_7638eb_idx'),
    ('merit6', 'merits_6_Roll_9e7c63_idx', 'cheradip_me_Roll_9f32f7_idx'),
    ('merit6', 'merits_6_Subject_5e12b4_idx', 'cheradip_me_Subject_07a594_idx'),
    ('notification', 'notificatio_is_acti_032af9_idx', 'cheradip_no_is_acti_a0729e_idx'),
    ('notification', 'notificatio_created_e4c995_idx', 'cheradip_no_created_399db9_idx'),
    ('order', 'orders_usernam_9b66d0_idx', 'cheradip_or_usernam_a22e95_idx'),
    ('order', 'orders_status_762191_idx', 'cheradip_or_status_fdc4e5_idx'),
    ('order', 'orders_custome_18fe5d_idx', 'cheradip_or_custome_15a929_idx'),
    ('orderdetail', 'order_detai_item_id_d9ba3b_idx', 'cheradip_or_item_id_2fe62d_idx'),
    ('ordered', 'ordered_usernam_2d14e8_idx', 'cheradip_or_usernam_3dc383_idx'),
    ('ordered', 'ordered_status_38eda7_idx', 'cheradip_or_status_b5d88a_idx'),
    ('ordered', 'ordered_custome_6b5b84_idx', 'cheradip_or_custome_5106a2_idx'),
    ('recommend', 'recommendat_EIIN_5f8ff6_idx', 'cheradip_re_EIIN_2f8bf9_idx'),
    ('recommend', 'recommendat_Roll_9943c2_idx', 'cheradip_re_Roll_7b6c88_idx'),
    ('recommend', 'recommendat_Name_55a0d3_idx', 'cheradip_re_Name_ce6395_idx'),
    ('recommend', 'recommendat_Subject_dd8c0c_idx', 'cheradip_re_Subject_169a7a_idx'),
    ('recommend', 'recommendat_status_88bbb1_idx', 'cheradip_re_status_b52f3f_idx'),
    ('recommend5', 'recommendat_EIIN_e28436_idx', 'cheradip_re_EIIN_21e16b_idx'),
    ('recommend5', 'recommendat_Subject_ea02c8_idx', 'cheradip_re_Subject_9688bc_idx'),
    ('recommend6', 'recommendat_EIIN_c0a574_idx', 'cheradip_re_EIIN_714195_idx'),
    ('recommend6', 'recommendat_Subject_86ceef_idx', 'cheradip_re_Subject_d46e97_idx'),
    ('subject', 'subjects_subject_e16b01_idx', 'cheradip_su_subject_7efab2_idx'),
    ('thana', 'thanas_distric_12070f_idx', 'cheradip_th_distric_953cad_idx'),
    ('thana', 'thanas_thana_n_0dc636_idx', 'cheradip_th_thana_n_9e7c73_idx'),
    ('thana', 'thanas_is_acti_fa8afd_idx', 'cheradip_th_is_acti_230e8f_idx'),
    ('token', 'tokens_Token_486bbd_idx', 'cheradip_to_Token_b3eb79_idx'),
    ('token', 'tokens_Status_83f054_idx', 'cheradip_to_Status_c5e731_idx'),
    ('token', 'tokens_purpose_ea833d_idx', 'cheradip_to_purpose_c9cbe4_idx'),
    ('topic', 'topics_chapter_5a7c61_idx', 'cheradip_to_chapter_eda33e_idx'),
    ('transaction', 'transaction_trxid_78c39c_idx', 'cheradip_tr_trxid_945175_idx'),
    ('transaction', 'transaction_usernam_ee0e5a_idx', 'cheradip_tr_usernam_e81d14_idx'),
    ('transaction', 'transaction_status_94cf9d_idx', 'cheradip_tr_status_b514b9_idx'),
    ('vacancy', 'vacancies_VPID_4f0c92_idx', 'cheradip_va_VPID_1d6421_idx'),
    ('vacancy', 'vacancies_EIIN_28022b_idx', 'cheradip_va_EIIN_f1c70b_idx'),
    ('vacancy', 'vacancies_Status_c960ee_idx', 'cheradip_va_Status_bebf5c_idx'),
    ('vacancy', 'vacancies_Distric_3168e4_idx', 'cheradip_va_Distric_70cd73_idx'),
    ('vacancy', 'vacancies_Subject_977dde_idx', 'cheradip_va_Subject_12656b_idx'),
    ('vacancy5', 'vacancies_5_VPID_939738_idx', 'cheradip_va_VPID_a9f18e_idx'),
    ('vacancy5', 'vacancies_5_EIIN_99e1d3_idx', 'cheradip_va_EIIN_6406a2_idx'),
    ('vacancy5', 'vacancies_5_Status_f70d9b_idx', 'cheradip_va_Status_917db9_idx'),
    ('vacancy5', 'vacancies_5_Distric_a96db8_idx', 'cheradip_va_Distric_3440de_idx'),
    ('vacancy6', 'vacancies_6_VPID_875d2a_idx', 'cheradip_va_VPID_d9458d_idx'),
    ('vacancy6', 'vacancies_6_EIIN_3c7632_idx', 'cheradip_va_EIIN_9c7f56_idx'),
    ('vacancy6', 'vacancies_6_Status_b9fa8b_idx', 'cheradip_va_Status_959c0f_idx'),
    ('vacancy6', 'vacancies_6_Distric_1749b6_idx', 'cheradip_va_Distric_6d056e_idx'),
    ('year', 'years_year_co_ddc639_idx', 'cheradip_ye_year_co_4bd43e_idx'),
]


def _model_name_to_table(apps, model_name):
    """Resolve model name to db table name (after 0008, tables have cheradip_ prefix)."""
    try:
        # Django uses lowercase model names in migrations
        model = apps.get_model('cheradip', model_name)
        return model._meta.db_table
    except LookupError:
        return None


def rename_indexes_conditionally(apps, schema_editor):
    """Rename indexes only when the old index exists (avoids 1091 when DB was created differently)."""
    conn = schema_editor.connection
    if conn.vendor == 'sqlite':
        return  # SQLite has no information_schema; index names differ. Skip for SQLite.

    try:
        from pymysql.err import OperationalError as PyOperationalError
    except ImportError:
        PyOperationalError = OperationalError

    db_name = conn.settings_dict['NAME']

    with conn.cursor() as cursor:
        for model_name, old_name, new_name in INDEX_RENAMES:
            table = _model_name_to_table(apps, model_name)
            if not table:
                continue
            # Check if old index exists
            cursor.execute(
                """
                SELECT COLUMN_NAME, NON_UNIQUE
                FROM information_schema.STATISTICS
                WHERE TABLE_SCHEMA = %s AND TABLE_NAME = %s AND INDEX_NAME = %s
                ORDER BY SEQ_IN_INDEX
                """,
                [db_name, table, old_name],
            )
            rows = cursor.fetchall()
            if not rows:
                continue
            columns = [r[0] for r in rows]
            non_unique = rows[0][1]
            cols_sql = ', '.join([f'`{c}`' for c in columns])
            unique_sql = '' if non_unique else 'UNIQUE '
            try:
                cursor.execute(f'ALTER TABLE `{table}` DROP INDEX `{old_name}`')
                cursor.execute(f'ALTER TABLE `{table}` ADD {unique_sql}INDEX `{new_name}` ({cols_sql})')
            except (OperationalError, PyOperationalError) as e:
                errno = getattr(e, 'args', [None])[0] if e.args else None
                if errno == 1091:
                    continue  # index didn't exist, skip
                raise


def noop_reverse(apps, schema_editor):
    pass


def alter_country_table_if_needed(apps, schema_editor):
    """Rename country table to cheradip_country only if cheradip_country does not already exist."""
    conn = schema_editor.connection
    if conn.vendor == 'sqlite':
        return  # SQLite: migration 0025_sqlite_country_table renames cheradip_countries -> cheradip_country

    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM information_schema.tables "
            "WHERE table_schema = DATABASE() AND table_name = 'cheradip_country'"
        )
        if cursor.fetchone():
            return  # cheradip_country already exists, nothing to do
        # Try renaming from cheradip_countries (after 0008) or countries
        for old_name in ('cheradip_countries', 'countries'):
            cursor.execute(
                "SELECT 1 FROM information_schema.tables "
                "WHERE table_schema = DATABASE() AND table_name = %s",
                [old_name],
            )
            if cursor.fetchone():
                cursor.execute(f"RENAME TABLE `{old_name}` TO `cheradip_country`")
                return


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0008_rename_tables_with_prefix'),
    ]

    operations = [
        migrations.RunPython(rename_indexes_conditionally, noop_reverse),
        migrations.RunPython(alter_country_table_if_needed, noop_reverse),
        # Update migration state only; DB rename is done by alter_country_table_if_needed when needed
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(name='country', table='cheradip_country'),
            ],
            database_operations=[],
        ),
    ]
