# Generated by Django 5.2.5 on 2026-09-22 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0008_ensure_trxmanagement_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorTopicIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(help_text='sha1 of db_alias|table|chapter|topic', max_length=64, unique=True)),
                ('db_alias', models.CharField(help_text="Django db alias holding table_name, e.g. 'hsc'", max_length=32)),
                ('table_name', models.CharField(max_length=96)),
                ('level_tr', models.CharField(blank=True, max_length=100)),
                ('class_level', models.CharField(blank=True, max_length=50)),
                ('subject_tr', models.CharField(blank=True, max_length=255)),
                ('subject_name', models.CharField(blank=True, help_text='Display name (Bangla aware)', max_length=255)),
                ('chapter_no', models.CharField(blank=True, max_length=50)),
                ('chapter', models.CharField(blank=True, max_length=255)),
                ('topic_no', models.CharField(blank=True, max_length=50)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=255)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('built_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cheradip_tutor_topic_index',
                'ordering': ['-question_count', 'topic'],
                'indexes': [models.Index(fields=['chapter'], name='cheradip_tu_chapter_b72e3e_idx'), models.Index(fields=['subject_tr'], name='cheradip_tu_subject_1ee164_idx'), models.Index(fields=['db_alias', 'table_name', 'chapter'], name='cheradip_tu_db_alia_020d18_idx'), models.Index(fields=['-question_count'], name='cheradip_tu_questio_2c3790_idx')],
            },
        ),
    ]
