# Generated by Django 5.0.6 on 2024-08-09 06:26

import cheradip.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0008_alter_customer_acctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.CharField(max_length=2)),
                ('chapter_name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='cheradip.subject')),
            ],
            options={
                'unique_together': {('subject', 'chapter_no')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_no', models.CharField(max_length=2)),
                ('topic_name', models.CharField(max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='cheradip.chapter')),
            ],
            options={
                'unique_together': {('chapter', 'topic_no')},
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_name', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='cheradip.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uddipok', models.TextField(blank=True, max_length=1000, null=True)),
                ('question', models.TextField(max_length=300)),
                ('option1', models.TextField(max_length=200)),
                ('option2', models.TextField(max_length=200)),
                ('option3', models.TextField(max_length=200)),
                ('option4', models.TextField(max_length=200)),
                ('answer', models.CharField(choices=[('option1', 'ক'), ('option2', 'খ'), ('option3', 'গ'), ('option4', 'ঘ')], max_length=7)),
                ('explanation', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cheradip.models.question_image_path)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('board', models.CharField(blank=True, max_length=14, null=True)),
                ('test', models.CharField(blank=True, max_length=100, null=True)),
                ('book', models.CharField(blank=True, max_length=100, null=True)),
                ('qid', models.CharField(editable=False, max_length=10, unique=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cheradip.chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cheradip.subject')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='cheradip.subtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cheradip.topic')),
            ],
        ),
    ]
