# Generated by Django 5.0.6 on 2024-08-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0009_subject_chapter_topic_subtopic_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='MCQ_ICT',
        ),
    ]
