# Generated by Django 5.2.5 on 2026-10-01 18:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0009_tutortopicindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=12)),
                ('badge', models.CharField(default='Star', max_length=20)),
                ('metric_name', models.CharField(default='exams_attended', max_length=32)),
                ('metric_count', models.PositiveIntegerField(default=0)),
                ('recent_metric_count', models.PositiveIntegerField(default=0)),
                ('passing_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('reference_value_percent', models.PositiveSmallIntegerField(default=20)),
                ('cq_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mcq_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('maintenance_met', models.BooleanField(default=True)),
                ('next_badge', models.CharField(blank=True, max_length=20)),
                ('next_metric_target', models.PositiveIntegerField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Membership progress',
                'db_table': 'cheradip_membership_progress',
            },
        ),
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('duration_months', models.PositiveSmallIntegerField(default=1)),
                ('track', models.CharField(choices=[('academic', 'Academic'), ('admission', 'Admission'), ('combined', 'Combined')], max_length=20)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cheradip_package_plans',
                'ordering': ['sort_order', 'duration_months', 'track'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='cheradip_pa_is_acti_07e4f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PackageSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('badge_discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=80)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='cheradip.packageplan')),
            ],
            options={
                'db_table': 'cheradip_package_subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status', 'ends_at'], name='cheradip_pa_custome_7f4293_idx')],
            },
        ),
    ]
