# Generated by Django 5.0.6 on 2024-08-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0010_rename_question_mcq_ict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq_ict',
            name='book',
        ),
        migrations.RemoveField(
            model_name='mcq_ict',
            name='test',
        ),
        migrations.AlterField(
            model_name='mcq_ict',
            name='answer',
            field=models.CharField(choices=[('1', 'ক'), ('2', 'খ'), ('3', 'গ'), ('4', 'ঘ')], max_length=1),
        ),
        migrations.AlterField(
            model_name='mcq_ict',
            name='board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
