# Generated by Django 5.2.5 on 2026-10-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0020_supersede_free_when_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='acctype',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('JobSeeker', 'Job Seeker'), ('Others', 'Others')], default='Student', max_length=12),
        ),
    ]
