# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheradip', '0034_add_teacher_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheradipJobseeker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=31)),
                ('username', models.CharField(db_index=True, max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=20, null=True)),
                ('group', models.CharField(blank=True, max_length=30, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, default='Male', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cheradip Job Seeker',
                'verbose_name_plural': 'Cheradip Job Seekers',
                'db_table': 'cheradip_jobseeker',
                'ordering': ['-date_joined'],
                'indexes': [
                    models.Index(fields=['username'], name='cheradip_js_username_idx'),
                    models.Index(fields=['email'], name='cheradip_js_email_idx'),
                    models.Index(fields=['country_code'], name='cheradip_js_country_idx'),
                ],
            },
        ),
    ]
