# Generated by Django 5.2.5 on 2026-08-06 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('birth_day', models.PositiveSmallIntegerField()),
                ('birth_month', models.PositiveSmallIntegerField()),
                ('birth_year', models.PositiveSmallIntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Child profile',
                'verbose_name_plural': 'Child profiles',
                'db_table': 'cc_children',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
                'db_table': 'cc_contests',
            },
        ),
        migrations.CreateModel(
            name='FriendCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=80)),
                ('name_bn', models.CharField(blank=True, default='', max_length=80)),
                ('image_ref', models.CharField(blank=True, default='', max_length=200)),
                ('greeting_audio_ref', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Friend character',
                'verbose_name_plural': 'Friend characters',
                'db_table': 'cc_friend_characters',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('title_en', models.CharField(max_length=80)),
                ('title_bn', models.CharField(blank=True, default='', max_length=80)),
                ('icon_name', models.CharField(help_text='Android drawable name, e.g. di_friends', max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Dashboard module',
                'verbose_name_plural': 'Dashboard modules',
                'db_table': 'cc_modules',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('replace_device', 'Replace device')], max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP code',
                'verbose_name_plural': 'OTP codes',
                'db_table': 'cc_otp_codes',
            },
        ),
        migrations.CreateModel(
            name='ParentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parent account',
                'verbose_name_plural': 'Parent accounts',
                'db_table': 'cc_parents',
            },
        ),
        migrations.CreateModel(
            name='ShortVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('media_url', models.CharField(max_length=500)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('age_tag', models.CharField(blank=True, default='2-6', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Short video',
                'verbose_name_plural': 'Short videos',
                'db_table': 'cc_short_videos',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('media_path', models.CharField(blank=True, default='', max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to='childcare.childprofile')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='childcare.contest')),
            ],
            options={
                'verbose_name': 'Contest entry',
                'verbose_name_plural': 'Contest entries',
                'db_table': 'cc_contest_entries',
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='childcare.childprofile')),
            ],
            options={
                'verbose_name': 'Drawing',
                'verbose_name_plural': 'Drawings',
                'db_table': 'cc_drawings',
            },
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_key', models.SlugField(max_length=40)),
                ('score', models.IntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to='childcare.childprofile')),
            ],
            options={
                'verbose_name': 'Game score',
                'verbose_name_plural': 'Game scores',
                'db_table': 'cc_game_scores',
            },
        ),
        migrations.CreateModel(
            name='LessonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, default='', help_text='e.g. capital, small, numbers, signs, alphabet, body_parts', max_length=40)),
                ('label_en', models.CharField(max_length=120)),
                ('label_bn', models.CharField(blank=True, default='', max_length=120)),
                ('image_ref', models.CharField(blank=True, default='', help_text='drawable or URL', max_length=200)),
                ('audio_ref', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='childcare.module')),
            ],
            options={
                'verbose_name': 'Lesson item',
                'verbose_name_plural': 'Lesson items',
                'db_table': 'cc_lesson_items',
                'ordering': ['module_id', 'section', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='childcare.module'),
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('device_label', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='childcare.parentaccount')),
            ],
            options={
                'verbose_name': 'Device session',
                'verbose_name_plural': 'Device sessions',
                'db_table': 'cc_device_sessions',
            },
        ),
        migrations.AddField(
            model_name='childprofile',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='childcare.parentaccount'),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='started', max_length=32)),
                ('score', models.IntegerField(default=0)),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='childcare.childprofile')),
                ('lesson_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress', to='childcare.lessonitem')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='childcare.module')),
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progress',
                'db_table': 'cc_progress',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('section', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='childcare.module')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'cc_quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('prompt_audio_ref', models.CharField(blank=True, default='', max_length=200)),
                ('prompt_image_ref', models.CharField(blank=True, default='', max_length=200)),
                ('choices_json', models.JSONField(default=list, help_text='["A","B","C","D"]')),
                ('correct_index', models.PositiveSmallIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='childcare.quiz')),
            ],
            options={
                'verbose_name': 'Quiz question',
                'verbose_name_plural': 'Quiz questions',
                'db_table': 'cc_quiz_questions',
                'ordering': ['quiz_id', 'sort_order', 'id'],
            },
        ),
    ]
